### ISSUE TITLE
Bridgeサンプル問題設計案

### ISSUE THREAD

**Issue by y-yamashita-git** [y-yamashita-git/ProgramDesignPJ#14]
@wamomo-m 

### サンプル問題提案
- 問題:召喚画面の作成
- 用意クラス
　- `Summon`->Abstractionに該当
　- `SummonImpl`->Implementerに該当
　- `Genshin`->RefineAbstractionに該当
　- `RyuseiImpl`->ConcreteImplementerに該当

---MEMO---
### Bridgeとは
- 機能と実装の橋渡し役

### Bridgeの基本構造
- `Abstraction` :機能のTemp
- `Implementer` :実装のTemp
- `RefineAbstraction` :機能の継承
- `ConcreteImplementer` :実装の継承

### 参考文献
https://www.techscore.com/tech/DesignPattern/Bridge
https://www.pgls-kl.com/article/article_82.html

**Comment by wamomo-m** [comment]
実装クラスのクラス名に Imp をつけるのを見たことがない (調べた感じ多くは Impl だと思います) のですが、何か参考にしたものはありますか？

**Comment by y-yamashita-git** [comment]
@wamomo-m 

> 参考にしたものはありますか

[このサイト](https://www.pgls-kl.com/article/article_82.html) を見てやってましたが、ImplかImでした。訂正します

**Comment by wamomo-m** [comment]
今回のデザインパターンの場合、クラス名だけだといまいちどういうものを作ろうとしてるのかイメージが湧かなかったので、あとは任せました…(力尽きた)
個人的にはこのサイトがアンチパターンから紹介していてわかりやすかったです！
https://qiita.com/sfdslkl/items/56e08ea6337e21b0054e
