### ISSUE TITLE
Builderサンプル問題設計案

### ISSUE THREAD

**Issue by y-yamashita-git** [y-yamashita-git/ProgramDesignPJ#4]
### サンプル問題提案
- 問題:教室の生成
- 用意クラス
　- School(教室名(String型:1-6など)、教室内容(Builder))->Director
　- Class(担任名、サブ担任、生徒リスト)->Builderクラス
　- Class_A(担任名、サブ担任、生徒リスト)->Builder継承クラス1
　- Class_B(担任名)->Builder継承クラス2
- 必須メンバ変数:担任(String)、生徒リスト(Array)
- 任意メンバ変数:サブ担任(String)

### 備考
- どこまでひな壇決めればいいかわからなかったので、今後の意見が欲しいです

---MEMO---
### Builderとは
- オブジェクトの生成過程を抽象化する

### Builderメリット
- インスタンス生成時の複雑性を抑える
  - 任意の変数であればインスタンス生成時に引数を渡さなくてよい
  - 引数の順番の渡し間違えリスクの削減

### Builderの基本構成
- Directorクラス(Builderの生成指定)
- Builderクラス
- Builderを継承したクラス

### 参考文献
https://www.techscore.com/tech/DesignPattern/Builder

**Comment by wamomo-m** [comment]
@y-yamashita-git メンションくれないと気づけないです...

**Comment by wamomo-m** [comment]
@y-yamashita-git 

参考文献 URL で貼ってくれてるのありがたかったわ～！

今回のテーマは School を生成するイメージで、Class (教室) には Student、Teacher がいる、
くらいの軽いイメージだった、でもここまで決めとくと結構楽かもね！

クラス名の意図じゃなかったかもしれないけど、`Class_A`、`Class_B` じゃなくて、
`Class`、`ClassWithSubTeacher` みたいにクラスのタイプ名にするといいかもしれません
`Class_A` だと固有名詞「Aクラス」専用の Builder に見えます
そうすると、クラス (教室の組) 毎に Builder を継承したクラスを作る必要があるように見えてしまいます
実際にこのコードを使用するのに、それが現実的でないことはわかるでしょうか？

いかがでしょうか？

**Comment by y-yamashita-git** [comment]
@wamomo-m 

クラス名納得しました。
名前考えるのも設計の一つの課題ですね。
