### ISSUE TITLE
Factory Methods設計案

### ISSUE THREAD

**Issue by y-yamashita-git** [y-yamashita-git/ProgramDesignPJ#6]
@wamomo-m 

### サンプル問題提案
- 問題:アカウント作成(AbstractFactoryと同様)
- 用意クラス
　- `Account`->Factoryに該当
　- `CreateAccountProduct`->Productに該当
　　- メソッド
　　　- CreateName(String):Nameクラス
　　　- CreateEmail(String):Emailクラス
　- `CreateAccount`->CreateFactoryに該当
　- `GoogleAccount`:Product継承クラス1
　- `Yahoo Account`:Product継承クラス2
　- その他クラス
　　- `Name`
　　- `Email`

---MEMO---
### Factory Methodsとは
- インスタンス作成時、サブクラスに処理を任せるデザインパターン

### FactoryMethodの基本構成
- `Factory` :Product を生成
- `Product` :ConcreteProductのインタフェースを定義
- `CreateFactory` :Factoryクラス
- `ConcreteProduct` :Product継承クラス

### 参考文献
https://www.techscore.com/tech/DesignPattern/FactoryMethod

**Comment by wamomo-m** [comment]
@y-yamashita-git 

> - その他クラス
> 　　- Name
> 　　- Email

値オブジェクトとして扱う、という意味合いでしたら良い設計かとも思いますが、
Factory Method を学ぶ、という意味合いで複雑さを排除するために
単純な string 型メンバ変数でもよいのかなと思ったのですがいかがでしょうか

- 参考: 値オブジェクト
  - https://qiita.com/wanko5296/items/8b470934cdc14f869a91

--

`CreateAccountProduct` などのクラス名が動詞で始まるものを見たことがないのですが
これは何か参考にしたものがありますか？

Factory に関係するクラスの場合、create よりも factory を使うほうが良い気がします

-- 

私が Factory Method を学んだ感じ、どちらかというと
Factory: AccountFactory、Product: Account というイメージだったのですが、
この構造にした考えを聞いてもよいですか？

Product を Account にした場合、こういう形になるかと思いました！

- https://www.pgls-kl.com/article/article_80.html

--

あとごめん、これは誤字って認識でいい？

> Builderの基本構成

**Comment by y-yamashita-git** [comment]
@wamomo-m 

> 値オブジェクトとして扱う、という意味合いでしたら良い設計かとも思いますが、
Factory Method を学ぶ、という意味合いで複雑さを排除するために
単純な string 型メンバ変数でもよいのかなと思ったのですがいかがでしょうか

確かに。前回とできるだけ一緒にして構成の違い見ようかなと思ってましたが、こちらに関しては一緒にしなくてもただ文字列として入れれば解決なのでいいと思います。ではその他話の方向で進めます。

------

> `CreateAccountProduct` などのクラス名が動詞で始まるものを見たことがないのですが
これは何か参考にしたものがありますか？

特にありません。今回はAccount処理を作成するという意味合いでこちらの名前にしてました。
ただ以下のURLを見た時にクラス名は名詞動名詞だそうなので、やるとしたら`MakingAccount`とかだったのかなと思いました。

文献: https://qiita.com/Koki_jp/items/f3d3e824f98d182d4100

> Factory に関係するクラスの場合、create よりも factory を使うほうが良い気がします

確かに。Factoryだとわかりやすいですね。GoFでFacroty使う時会社とかはFactoryってつけるのか不安だったんで今回使ってませんでした。

---------------

> 私が Factory Method を学んだ感じ、どちらかというと
Factory: AccountFactory、Product: Account というイメージだったのですが、
この構造にした考えを聞いてもよいですか？

Product を Account にした場合、こういう形になるかと思いました！

Account Factory(CreateAccount Product)がAccountを作る処理って事で書いてたためこの構成になってました。ただ貼っていただいたURLみると確かにって思うとこもあります。

---------------

> あとごめん、これは誤字って認識でいい？

誤字です。前回の使いまわした時に変更し忘れました。すみません
