### ISSUE TITLE
Singletonのサンプル問題提案

### ISSUE THREAD

**Issue by y-yamashita-git** [y-yamashita-git/ProgramDesignPJ#9]
@wamomo-m 

### サンプル問題提案
- 問題:パソコン情報(Macアドレス)
- 用意クラス
　- `Computer`->Aingletonに該当
　　- 変数：`mac_address`

---MEMO---
### Singletonとは
- インスタンスが1つしか存在しないデザインパターン
- config(設定ファイル)のようなもの？(自分の認識)

### Singletonの基本構成
- `Singleton` 

### 参考文献
https://qiita.com/shoheiyokoyama/items/c16fd547a77773c0ccc1
http://www.code-magagine.com/?p=2693

**Comment by wamomo-m** [comment]
これは、Computer というクラスのインスタンスが唯一、という意味ですか？それとも 変数 mac_address が唯一という意味ですか？
それによって意味が変わるような気がしました！

**Comment by wamomo-m** [comment]
@y-yamashita-git

**Comment by y-yamashita-git** [comment]
@wamomo-m 

Computerというクラスのインスタンスが唯一ということです

**Comment by wamomo-m** [comment]
@y-yamashita-git 
うーん、Computer 自体はこの世にたくさんあって、プログラムを書くときにこの命名だと唯一のインスタンスっていうイメージが湧きにくいなぁと感じました…。

全然このクラスで Singleton 自体のコードを書くことは可能だとは思います！

後からこの Computer クラスを使うってなった時に逆に Singleton になってるのに気づかず使ってしまいそうな…そこにちょっとだけ違和感を感じました。

**Comment by y-yamashita-git** [comment]
@wamomo-m 
あーなるほど。
特定のという要素がないと今後的な目線がありますね

例えばTiriyamaComputerとかだと
塵山のパソコンになるから良かったりします？

**Comment by wamomo-m** [comment]
@y-yamashita-git 
はい、そういう認識です。
